'\" t
.\"     Title: spacebar
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2021-04-08
.\"    Manual: spacebar manual
.\"    Source: spacebar
.\"  Language: English
.\"
.TH "SPACEBAR" "1" "2021-04-08" "spacebar" "spacebar manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
spacebar \- a simple status bar for macOS
.SH "SYNOPSIS"
.sp
\fBspacebar\fP [\fB\-v\fP,\fB\-\-version\fP|\fB\-V\fP,\fB\-\-verbose\fP|\fB\-m\fP,\fB\-\-message\fP \fImsg\fP|\fB\-c\fP,\fB\-\-config\fP \fIconfig_file\fP]
.SH "DESCRIPTION"
.sp
\fBspacebar\fP is a simple status bar for macOS.
.SH "OPTIONS"
.sp
\fB\-v\fP, \fB\-\-version\fP
.RS 4
Print the version and exit.
.RE
.sp
\fB\-V\fP, \fB\-\-verbose\fP
.RS 4
Output debug information to stdout.
.RE
.sp
\fB\-m\fP, \fB\-\-message\fP \fI<msg>\fP
.RS 4
Send message to a running instance of spacebar.
.RE
.sp
\fB\-c\fP, \fB\-\-config\fP \fI<config_file>\fP
.RS 4
Use the specified configuration file.
.RE
.SH "CONFIG"
.SS "General Syntax"
.sp
spacebar \-m config <setting>
.RS 4
Get or set the value of <setting>.
.RE
.SS "Settings"
.sp
\fBdebug_output\fP [\fI<BOOL_SEL>\fP]
.RS 4
Enable output of debug information to stdout.
.RE
.sp
\fBdisplay\fP [\fI<display>\fP]
.RS 4
Display to draw the bar on.
.br
Must be one of \fImain\fP or \fIall\fP.
.RE
.sp
\fBposition\fP [\fI<position>\fP]
.RS 4
Position on the screen to draw the bar.
.br
Must be one of \fItop\fP or \fIbottom\fP.
.RE
.sp
\fBheight\fP [\fI<NUM>\fP]
.RS 4
Height in pixels to draw the bar.
.RE
.sp
\fBtitle\fP [\fI<BOOL_SEL>\fP]
.RS 4
Enable focused window title display at the centre of the bar.
.br
This cannot be enabled when \fIcenter_shell\(cqis set to \(aqon\fP.
.RE
.sp
\fBspaces\fP [\fI<BOOL_SEL>\fP]
.RS 4
Enable space indicator on the left of the bar.
.RE
.sp
\fBspace_icon_strip\fP [\fI<sym_1> <sym_2> <sym_n>\fP]
.RS 4
Specify symbols separated by whitespace to be used for visualizing spaces.
.RE
.sp
\fBspaces_for_all_displays\fP [\fI<BOOL_SEL>\fP]
.RS 4
Enable space indicators for spaces on each display.
.RE
.sp
\fBspace_icon\fP [\fI<sym>\fP]
.RS 4
Specify a general symbol to use for any given space that does not have a match in \fIspace_icon_strip\fP.
.RE
.sp
\fBspace_icon_color\fP [\fI<COLOR>\fP]
.RS 4
Color to use for drawing the current space icon.
.RE
.sp
\fBspace_icon_color_secondary\fP [\fI<COLOR>\fP]
.RS 4
Color to use for drawing the current space icon of the second display.
.RE
.sp
\fBspace_icon_color_tertiary\fP [\fI<COLOR>\fP]
.RS 4
Color to use for drawing the current space icon of the third display.
.RE
.sp
\fBdisplay_separator\fP [\fI<BOOL_SEL>\fP]
.RS 4
Enable separator between the spaces for each display.
.RE
.sp
\fBdisplay_separator_icon\fP [\fI<sym>\fP]
.RS 4
Specify a symbol to use for the display separator.
.RE
.sp
\fBdisplay_separator_icon_color\fP [\fI<COLOR>\fP]
.RS 4
Color to use for drawing the display separator icon.
.RE
.sp
\fBclock\fP [\fI<BOOL_SEL>\fP]
.RS 4
Enable clock on the right of the bar.
.RE
.sp
\fBpower\fP [\fI<BOOL_SEL>\fP]
.RS 4
Enable power indicator on the right of the bar.
.RE
.sp
\fBpadding_left\fP [\fI<NUM>\fP]
.RS 4
Padding in pixels between the left edge of the display and the first item.
.RE
.sp
\fBpadding_right\fP [\fI<NUM>\fP]
.RS 4
Padding in pixels between the right edge of the display and the last item.
.RE
.sp
\fBspacing_left\fP [\fI<NUM>\fP]
.RS 4
Spacing in pixels between the left space indicators.
.RE
.sp
\fBspacing_right\fP [\fI<NUM>\fP]
.RS 4
Spacing in pixels between the right status segments.
.RE
.sp
\fBtext_font\fP [\fI<font_family>:<font_style>:<font_size>\fP]
.RS 4
Specify name, style and size of font to use for drawing text.
.br
Use \fIFont Book.app\fP to identify the correct name.
.RE
.sp
\fBicon_font\fP [\fI<font_family>:<font_style>:<font_size>\fP]
.RS 4
Specify name, style and size of font to use for drawing icon symbols.
.br
Use \fIFont Book.app\fP to identify the correct name.
.RE
.sp
\fBbackground_color\fP [\fI<COLOR>\fP]
.RS 4
Color to use for drawing status bar background.
.RE
.sp
\fBforeground_color\fP [\fI<COLOR>\fP]
.RS 4
Color to use for drawing status bar elements.
.RE
.sp
\fBpower_icon_strip\fP [\fI<sym_battery> <sym_ac>\fP]
.RS 4
Specify two symbols separated by whitespace.
.br
The first symbol represents battery power and the second symbol indicates AC.
.RE
.sp
\fBpower_icon_color\fP [\fI<COLOR>\fP]
.RS 4
Color to use for drawing the power (charging) icon.
.RE
.sp
\fBbattery_icon_color\fP [\fI<COLOR>\fP]
.RS 4
Color to use for drawing the battery icon.
.RE
.sp
\fBclock_icon\fP [\fI<sym>\fP]
.RS 4
Specify a symbol to represent the current time.
.RE
.sp
\fBclock_icon_color\fP [\fI<COLOR>\fP]
.RS 4
Color to use for drawing the clock icon.
.RE
.sp
\fBclock_format\fP [\fI<sym>\fP]
.RS 4
Specify a format for the current time, according to the strftime function.
.RE
.sp
\fBdnd\fP [\fI<BOOL_SEL>\fP]
.RS 4
Enable a DoNotDisturb indicator on the right of the bar.
.RE
.sp
\fBdnd_icon\fP [\fI<sym>\fP]
.RS 4
Specify a symbol to represent the current DoNotDisturb status.
.RE
.sp
\fBdnd_icon_color\fP [\fI<COLOR>\fP]
.RS 4
Color to use for drawing the DoNotDisturb icon.
.RE
.sp
\fBleft_shell\fP [\fI<BOOL_SEL>\fP]
.RS 4
Enable shell output on the left of the bar.
.RE
.sp
\fBright_shell\fP [\fI<BOOL_SEL>\fP]
.RS 4
Enable shell output on the right of the bar.
.RE
.sp
\fBcenter_shell\fP [\fI<BOOL_SEL>\fP]
.RS 4
Enable shell output at the center of the bar.
.br
This cannot be enabled when \fItitle\fP is set to \fIon\fP.
.RE
.sp
\fBleft_shell_icon\fP [\fI<sym>\fP]
.RS 4
Specify a symbol to prefix the left shell output.
.RE
.sp
\fBleft_shell_icon_color\fP [\fI<COLOR>\fP]
.RS 4
Color to use for drawing the left shell icon.
.RE
.sp
\fBleft_shell_command\fP [\fI<shell command>\fP]
.RS 4
Command pipeline to retrieve the output for displaying in the left shell section.
.br
There is NO timeout protection for the command pipeline, so be sure to set it to something that returns output quickly.
.RE
.sp
\fBright_shell_icon\fP [\fI<sym>\fP]
.RS 4
Specify a symbol to prefix the right shell output.
.RE
.sp
\fBright_shell_icon_color\fP [\fI<COLOR>\fP]
.RS 4
Color to use for drawing the right shell icon.
.RE
.sp
\fBright_shell_command\fP [\fI<shell command>\fP]
.RS 4
Command pipeline to retrieve the output for displaying in the right shell section.
.br
There is NO timeout protection for the command pipeline, so be sure to set it to something that returns output quickly.
.RE
.sp
\fBcenter_shell_command\fP [\fI<shell command>\fP]
.RS 4
Command pipeline to retrieve the output for displaying in the center shell section.
.br
There is NO timeout protection for the command pipeline, so be sure to set it to something that returns output quickly.
.br
.RE
.SH "EXIT CODES"
.sp
If \fBspacebar\fP can\(cqt handle a message, it will return a non\-zero exit code.
.SH "AUTHOR"
.sp
Calum MacRae <hi at cmacr.ae>