'\" t
.\"     Title: spacebar
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2020-07-17
.\"    Manual: Spacebar Manual
.\"    Source: Spacebar
.\"  Language: English
.\"
.TH "SPACEBAR" "1" "2020-07-17" "Spacebar" "Spacebar Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
spacebar \- Status bar for mac
.SH "SYNOPSIS"
.sp
\fBspacebar\fP [\fB\-v\fP,\fB\-\-version\fP|\fB\-V\fP,\fB\-\-verbose\fP|\fB\-m\fP,\fB\-\-message\fP \fImsg\fP|\fB\-c\fP,\fB\-\-config\fP \fIconfig_file\fP]
.SH "DESCRIPTION"
.sp
\fBspacebar\fP is a tiling window manager for macOS based on binary space partitioning.
.SH "OPTIONS"
.sp
\fB\-v\fP, \fB\-\-version\fP
.RS 4
Print the version and exit.
.RE
.sp
\fB\-V\fP, \fB\-\-verbose\fP
.RS 4
Output debug information to stdout.
.RE
.sp
\fB\-m\fP, \fB\-\-message\fP \fI<msg>\fP
.RS 4
Send message to a running instance of spacebar.
.RE
.sp
\fB\-c\fP, \fB\-\-config\fP \fI<config_file>\fP
.RS 4
Use the specified configuration file.
.RE
.SH "CONFIG"
.SS "General Syntax"
.sp
spacebar \-m config <setting>
.RS 4
Get or set the value of <setting>.
.RE
.SS "Settings"
.sp
\fBdebug_output\fP [\fI<BOOL_SEL>\fP]
.RS 4
Enable output of debug information to stdout.
.RE
.sp
\fBposition\fP [\fI<position>\fP]
.RS 4
Position on the screen to draw the bar.
.br
Must be one of \fItop\fP or \fIbottom\fP.
.RE
.sp
\fBheight\fP [\fI<NUM>\fP]
.RS 4
Height in pixels to draw the bar.
.RE
.sp
\fBtext_font\fP [\fI<font_family>:<font_style>:<font_size>\fP]
.RS 4
Specify name, style and size of font to use for drawing text.
.br
Use \fIFont Book.app\fP to identify the correct name.
.RE
.sp
\fBicon_font\fP [\fI<font_family>:<font_style>:<font_size>\fP]
.RS 4
Specify name, style and size of font to use for drawing icon symbols.
.br
Use \fIFont Book.app\fP to identify the correct name.
.RE
.sp
\fBbackground_color\fP [\fI<COLOR>\fP]
.RS 4
Color to use for drawing status bar background.
.RE
.sp
\fBforeground_color\fP [\fI<COLOR>\fP]
.RS 4
Color to use for drawing status bar elements.
.RE
.sp
\fBspace_icon_strip\fP [\fI<sym_1> <sym_2> <sym_n>\fP]
.RS 4
Specify symbols separated by whitespace to be used for visualizing spaces.
.RE
.sp
\fBpower_icon_strip\fP [\fI<sym_battery> <sym_ac>\fP]
.RS 4
Specify two symbols separated by whitespace.
.br
The first symbol represents battery power and the second symbol indicates AC.
.RE
.sp
\fBpower_icon_color\fP [\fI<COLOR>\fP]
.RS 4
Color to use for drawing the power (charing) icon.
.RE
.sp
\fBbattery_icon_color\fP [\fI<COLOR>\fP]
.RS 4
Color to use for drawing the battery icon.
.RE
.sp
\fBspace_icon\fP [\fI<sym>\fP]
.RS 4
Specify a general symbol to use for any given space that does not have a match in \fIspace_icon_strip\fP.
.RE
.sp
\fBspace_icon_color\fP [\fI<COLOR>\fP]
.RS 4
Color to use for drawing the current space icon.
.RE
.sp
\fBclock_icon\fP [\fI<sym>\fP]
.RS 4
Specify a symbol to represent the current time.
.RE
.sp
\fBclock_icon_color\fP [\fI<COLOR>\fP]
.RS 4
Color to use for drawing the clock icon.
.RE
.sp
\fBclock_format\fP [\fI<sym>\fP]
.RS 4
Specify a format for the current time, according to the strftime function.
.RE
.sp
\fBdnd_icon\fP [\fI<sym>\fP]
.RS 4
Specify a symbol to represent the current DoNotDisturb status.
.RE
.sp
\fBdnd_icon_color\fP [\fI<COLOR>\fP]
.RS 4
Color to use for drawing the DoNotDisturb icon.
.RE
.SH "EXIT CODES"
.sp
If \fBspacebar\fP can\(cqt handle a message, it will return a non\-zero exit code.
.SH "AUTHOR"
.sp
Calum MacRae <hi at cmacr.ae>
